/* 2026-10の合意を体験する独立デモ。Firebaseや外部サービスには接続しない。 */
(function () {
  'use strict';
  var M = window.YouiPilotEconomy, KEY = 'youi_pilot_20261008_v1';
  var app = document.getElementById('app'), nav = document.getElementById('app-nav');
  var state, registered = false, view = 'explore', selected = null, filter = 'all', walletActor = 'me';
  var metadata = {}, toastTimer;
  var templates = {
    talk: { name: '話し相手', title: '園芸や昔の仕事の話を、ゆっくり。', time: '木曜日 14:00〜14:30', place: '地域の交流スペース（架空）', duration: '30分', host: '交流スペースの担当者', about: '日常の会話を楽しむ時間。聞きたいこと、話したいことを大切にします。', scope: '初回はスタッフのいる場所で30分。介助・専門相談は担当者へつなぎます。', match: '話題への関心と、会話のペース・希望する距離感が合う相手を紹介します。', icon: '<path d="M18 20h43v29H39L25 61V49h-7z"/><path d="M66 34h17v30H71l-9 10V64H45V54"/><path d="M29 30h22M29 39h15"/>' },
    club: { name: '部活動の補助', title: '顧問と一緒に、準備と記録を。', time: '金曜日 16:00〜17:00', place: '協力校の体育館（架空）', duration: '60分', host: '協力校の顧問', about: '準備・練習記録・片付けを担当。できることを、顧問と確かめながら。', scope: '顧問が同席し、準備・記録・片付けを担当。専門的な指導は別の確認が必要です。', match: '希望する作業と経験、参加時間を確認し、受入側が担当する役割を説明します。', icon: '<rect x="26" y="17" width="48" height="55" rx="4"/><path d="M39 17v-6h22v6M38 31h24M38 42h24M38 53h15"/><path d="M18 32v33M83 23v33"/>' },
    cleanup: { name: 'まちの清掃', title: 'いつもの公園を、みんなで。', time: '日曜日 9:00〜10:00', place: '公園の入口（架空）', duration: '60分', host: '清掃活動の主催団体', about: '初めての参加も歓迎。道具は主催者が用意し、時間を決めて活動します。', scope: '区域を区切ってごみ拾い。危険物は責任者へ。雨天時は開始2時間前までに案内します。', match: '場所・時間・作業の負担を確認して申し込みます。主催者が受付と道具を案内します。', icon: '<path d="M20 69h65M28 64V37M17 39c-2-11 4-22 12-22s15 11 12 22zM62 68V39M53 39h23l-3 29H56zM50 34h29M59 29h11"/>' }
  };
  var statusNames = { draft: '内容の確認', reserved: '活動の予定', ready: '配布の準備完了', completed: '活動完了', hold: '運営が確認中', cancelled: '取り消し済み' };
  function esc(x) { return String(x == null ? '' : x).replace(/[&<>"']/g, function (c) { return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]; }); }
  function button(text, action, attrs, style, disabled) { return '<button type="button" class="button ' + (style || '') + '" data-action="' + action + '" ' + (attrs || '') + (disabled ? ' disabled' : '') + '>' + text + '</button>'; }
  function aid(id) { return 'data-id="' + esc(id) + '"'; }
  function name(id) { return esc(state.actors[id].name); }
  function activity() { return state.activities.find(function (a) { return a.id === selected; }); }
  function title(a) { return (metadata[a.id] || {}).title || templates[a.scenario].title; }
  function message(text) { var el = document.getElementById('toast'); el.textContent = text; el.classList.add('visible'); clearTimeout(toastTimer); toastTimer = setTimeout(function () { el.classList.remove('visible'); }, 4200); }
  function save() { try { localStorage.setItem(KEY, JSON.stringify({ state: state, registered: registered, metadata: metadata })); } catch (_) { message('この端末に保存できません。開いている間は体験できます。'); } }
  function dispatch(action, text) { try { state = M.reduce(state, action); save(); render(); if (text) message(text); return true; } catch (e) { message(e.message || '操作を確認してください。'); return false; } }
  function go(next) { view = next; render(); window.scrollTo(0, 0); app.focus({preventScroll:true}); }
  function hero(kicker, heading, sub, wallet) { return '<div class="hero"><div><div class="eyebrow">' + kicker + '</div><h1>' + heading + '</h1>' + (sub ? '<p class="intro">' + sub + '</p>' : '') + '</div>' + (wallet ? '<div class="wallet-mini"><span>あなたの＆ポイント</span><strong>' + state.actors.me.balance + '</strong><small>pt</small></div>' : '') + '</div>'; }
  function render() {
    nav.hidden = !registered;
    nav.innerHTML = [['explore','○','活動を探す'],['activities','⌁','活動中・履歴'],['wallet','＆','＆ポイント'],['profile','◇','マイページ']].map(function (n) { return '<button type="button" data-action="nav" data-view="'+n[0]+'" class="'+(view===n[0] || view==='detail' && n[0]==='activities' ? 'active' : '')+'"'+(view===n[0]?' aria-current="page"':'')+'><span class="nav-icon" aria-hidden="true">'+n[1]+'</span>'+n[2]+'</button>'; }).join('');
    if (!registered) { app.innerHTML = onboarding(); return; }
    app.innerHTML = view === 'explore' ? explore() : view === 'activities' ? activities() : view === 'detail' ? detail() : view === 'wallet' ? wallet() : profile();
  }
  function onboarding() {
    return '<div class="onboard"><div class="onboard-hero"><div class="eyebrow">YOU & I, SUPPORT EACH OTHER</div><h1>できることから、<br>結んでいく。</h1><p class="intro">支える日も、頼る日も。<br>小さな関わりが、次の機会につながる場所。</p></div><div class="principles"><div class="principle"><strong>01</strong>残高0でも<br>気兼ねなく頼れる</div><div class="principle"><strong>02</strong>活動が終わると<br>双方にポイント</div><div class="principle"><strong>03</strong>経験と信頼が<br>選べることになる</div></div><form class="panel" data-form="register"><h2>あなたの立場で、試してみる</h2><p class="subtle">実際の登録ではありません。仮の名前で体験できます。</p><label class="field"><span>デモでの呼び名</span><input name="name" maxlength="20" value="はる" autocomplete="off" required></label><label class="check-row"><input type="checkbox" name="understood" required><span>架空の活動・ポイントを使うデモであることを確認しました。</span></label><button class="button full" type="submit">0ptでデモをはじめる</button></form><p class="subtle">個人情報や身分証の入力は不要です。通常の依頼・応募にポイントは使いません。</p></div>';
  }
  function explore() {
    return hero('暮らしの中の、小さな支え合い', '今日は、どんな関わりを。', name('me') + 'さん。手伝うことも、頼むことも、同じ場所から。', true) + '<div class="cards">' + Object.keys(templates).map(function (key, i) { var t=templates[key]; return '<article class="card"><div class="card-art '+key+'"><span class="category-num">0'+(i+1)+' / SPACE</span><svg viewBox="0 0 100 85" aria-hidden="true">'+t.icon+'</svg></div><div class="card-body"><h3>'+t.name+'</h3><div class="tag-row"><span class="tag">'+t.duration+'</span><span class="tag">'+(key==='cleanup'?'5人の活動':'1対1')+'</span></div><p>'+t.about+'</p><div class="actions">'+button('手伝ってみる','create','data-scenario="'+key+'" data-role="provider"')+button(key!=='talk'?'主催を試す':'依頼してみる','create','data-scenario="'+key+'" data-role="receiver"','secondary')+'</div></div></article>'; }).join('') + '</div><div class="panel soft"><div class="row"><div><h3>支える人にも、次の選択肢を。</h3><p class="subtle">＆ポイントは使える残高。信頼と経験は、担える役割の記録です。</p></div>'+button('仕組みを見る','guide','','secondary small')+'</div></div><p class="subtle">デモでは1人10ptを仮の配布額にしています。実際の提供先・発行枠は実証前に決めます。</p>';
  }
  function activities() {
    return hero('ACTIVITIES','活動中・これまでの関わり','完了確認と相互評価は別々に進めます。評価が未入力でも、次の依頼を利用できます。')+(state.activities.length?state.activities.slice().reverse().map(function(a){return '<button class="list-card" data-action="open" '+aid(a.id)+'><div class="row"><div><span class="eyebrow">'+templates[a.scenario].name+'</span><h3>'+esc(title(a))+'</h3><p class="subtle">'+(a.scenario==='cleanup'?'参加者 '+a.providerIds.length+'人・主催団体':'支援者・受援者 各1人')+'</p></div><span class="status '+(a.status==='completed'?'complete':'')+'">'+statusNames[a.status]+'</span></div></button>';}).join(''):'<div class="panel empty"><h2>最初の関わりを、ここから。</h2><p>3つの活動から「手伝う」「頼む」を選んでみましょう。</p><div class="actions">'+button('活動を探す','nav','data-view="explore"')+'</div></div>');
  }
  function detail() {
    var a=activity(); if(!a)return activities(); var t=templates[a.scenario], meta=metadata[a.id]||{};
    var stage=a.status==='draft'?0:a.status==='completed'?3:a.status==='ready'?2:1;
    var header=button('← 活動一覧','nav','data-view="activities"','secondary small')+'<div style="height:20px"></div>'+hero(t.name,esc(title(a)),'<span class="status '+(a.status==='completed'?'complete':'')+'">'+statusNames[a.status]+'</span>')+'<div class="step-track">'+['内容・相手の確認','活動・完了確認','双方に配布','相互評価・次の機会'].map(function(s,i){return '<div class="step '+(i<=stage?'done':'')+'">'+(i+1)+'. '+s+'</div>';}).join('')+'</div>';
    var common='<div class="panel"><h3>今回の約束</h3><dl class="details"><dt>場所</dt><dd>'+esc(meta.place||t.place)+'</dd><dt>日時</dt><dd>'+esc(meta.time||t.time)+'</dd><dt>担当者</dt><dd>'+t.host+'</dd><dt>すること</dt><dd>'+esc(meta.details||t.scope)+'</dd></dl><div class="note">'+t.match+'</div><h3 style="margin-top:23px">達成したら受け取るポイント</h3>'+a.rewards.map(function(r){return '<div class="row" style="margin-top:12px"><span class="subtle">'+name(r.actorId)+' <small>（'+(r.role==='provider'?'支援者':a.scenario==='cleanup'?'主催団体':'受援者')+'）</small></span><strong>'+r.points+' pt</strong></div>';}).join('')+'<p class="subtle" style="margin-top:13px">評価の高さによって配布量は変わりません。清掃の主催側は、1開催につき1回の配布です。</p></div>';
    var controls='';
    if(a.status==='draft') controls='<div class="panel"><h2>この内容で、つながる</h2><p class="subtle">双方が内容に同意した場面を試します。成立時に'+a.rewardTotal+'pt分の発行枠を確保します。</p><div class="actions">'+button('内容を確認して成立させる','reserve',aid(a.id))+'</div><div class="note">残高0ptでも成立できます。発行枠が不足する場合は、配布を約束する前にご案内します。</div></div>';
    else if(a.status==='reserved'||a.status==='ready') controls='<div class="panel"><h2>活動の完了を確かめる</h2><p class="subtle">約束した活動が行われたか、参加者と担当者がそれぞれ確認します。</p><div class="demo-controls"><p>デモ操作：各参加者の立場で完了確認を試せます。</p>'+a.requiredConfirmers.map(function(id){return '<div class="row"><span>'+name(id)+'</span>'+button(a.confirmations[id]?'確認済み':'完了を確認','confirm',aid(a.id)+' data-actor="'+id+'"','secondary small',!!a.confirmations[id])+'</div>';}).join('')+'<div class="row"><span>実証担当者</span>'+button(a.verification?'実施確認済み':'実施を確認','verify',aid(a.id),'quiet small',!!a.verification)+'</div></div><div class="actions">'+button('確認済みの全員へ配布する','award',aid(a.id),'',a.status!=='ready')+'</div><p class="subtle" style="margin-top:12px">配布は1活動につき一度だけ。相互評価の入力は配布の条件ではありません。</p><div class="actions">'+button('中断・認識の相違を報告','hold',aid(a.id),'secondary small')+button('活動を取り消す','cancel',aid(a.id),'secondary small')+'</div></div>';
    else if(a.status==='hold') controls='<div class="panel"><h2>運営が内容を確認しています</h2><p>実施内容が確認できるまで、配布は保留です。</p><div class="demo-controls"><p>デモ操作：担当者が確認した後の対応を試します。</p><div class="actions">'+button('内容を確認して再開','resolve',aid(a.id)+' data-outcome="resume"','secondary')+button('取り消す','resolve',aid(a.id)+' data-outcome="cancel"','secondary')+'</div></div></div>';
    else if(a.status==='cancelled') controls='<div class="panel"><h2>活動を取り消しました</h2><p>ポイントの配布はありません。確保していた発行枠は解放されました。</p><div class="actions">'+button('次の活動を探す','nav','data-view="explore"')+'</div></div>';
    else controls=reviewPanel(a);
    return header+'<div class="split"><div>'+controls+'</div><aside>'+common+'</aside></div>';
  }
  function reviewPanel(a) {
    var acting=a.meRole==='receiver'&&a.scenario!=='talk'?'organization':'me';
    var tasks=M.getReviewTasks(state,a.id), visible=M.getReviews(state,a.id,acting);
    return '<div class="panel"><h2>活動が、次につながりました。</h2><div class="note success">双方への配布と活動記録が完了しました。'+name(acting)+'の残高は '+state.actors[acting].balance+'pt です。</div><h3 style="margin-top:24px">お互いの関わりを振り返る</h3><p class="subtle">約束・役割・配慮を確認します。相性は信頼の条件に含めません。</p><div class="demo-controls"><p>デモ操作：相手・主催者の立場での回答も体験できます。</p><div class="review-list">'+tasks.map(function(task){return '<div class="review-item"><div class="row"><div><strong>'+name(task.fromActorId)+' → '+name(task.toActorId)+'</strong><p>'+(task.status==='expired'?'締切になりました。未回答は評価に含めません':task.status==='published'?'双方の回答または締切により反映済み':task.submitted?'相手の回答・締切を待っています':'まだ回答していません')+'</p></div>'+button(task.status==='expired'?'未回答で終了':task.submitted?'提出済み':'振り返る','review',aid(a.id)+' data-from="'+task.fromActorId+'" data-to="'+task.toActorId+'"','secondary small',task.submitted||task.status==='expired')+'</div></div>';}).join('')+'</div>'+button('7日後の状態を試す','advance','','quiet small')+'</div><p class="subtle" style="margin-top:15px">'+name(acting)+'宛てに確認できる評価：'+visible.filter(function(r){return r.toActorId===acting;}).length+'件。未入力は低評価にならず、ポイントにも影響しません。</p><div class="actions">'+button('マイページで経験を見る','nav','data-view="profile"')+button('＆ポイントを使う','nav','data-view="wallet"','secondary')+'</div><div class="actions">'+button('次回も同じ内容で試す','repeat',aid(a.id),'secondary small')+button('別の活動を探す','nav','data-view="explore"','secondary small')+'</div></div>';
  }
  function wallet() {
    var user=state.actors[walletActor], e=M.getEconomy(state);
    var catalog=state.catalog.filter(function(p){return filter==='all'||p.kind===filter;});
    var owned=state.redemptions.filter(function(r){return r.actorId===walletActor;});
    return hero('＆POINTS','次の楽しみを、選ぶ。','活動を成立させた双方へ。受け取ったポイントを使うと、その分が消却されます。')+'<div class="toolbar">'+button('あなたのポイント','wallet-actor','data-actor="me"','secondary '+(walletActor==='me'?'active':''))+button('主催団体のポイントを確認','wallet-actor','data-actor="organization"','secondary '+(walletActor==='organization'?'active':''))+'</div><div class="balance-hero"><p>'+esc(user.name)+'の＆ポイント</p><div class="amount">'+user.balance+' <small>pt</small></div><p>使っても、経験や信頼の記録は減りません。</p></div>'+(walletActor==='organization'?'<div class="note">団体のポイントは団体の活動に使う想定です。このデモでは、活動に関わるSpaceの体験枠だけを選べます。</div>':'')+'<div class="toolbar">'+[['all','すべて'],['tangible','商品・サービス'],['space','Spaceの体験']].map(function(f){return button(f[1],'filter','data-filter="'+f[0]+'"','secondary '+(filter===f[0]?'active':''));}).join('')+'</div><div class="cards">'+catalog.map(function(p){var blocked=walletActor==='organization'&&p.kind==='tangible';return '<article class="card reward-card"><span class="tag '+(p.kind==='space'?'blue':'green')+'">'+(p.kind==='space'?'Spaceの体験':'商品・サービス')+'</span><h3 style="margin-top:13px">'+esc(p.title)+'</h3><p>架空の交換先です。実際の利用券や商品は発行されません。</p><div class="row"><span class="cost">'+p.points+' <small>pt</small></span><span class="subtle">残り '+p.stock+' 枠</span></div><div class="actions">'+button(blocked?'団体では選べません':p.stock===0?'受付終了':user.balance<p.points?'ポイントが足りません':'この特典を選ぶ','redeem',aid(p.id),'',blocked||p.stock===0||user.balance<p.points)+'</div></article>';}).join('')+'</div><div class="panel"><h2>交換の記録</h2>'+(owned.length?owned.slice().reverse().map(function(r){return '<div class="row" style="margin-top:15px"><div><h3>'+esc(r.title)+'</h3><p class="subtle">'+r.points+'pt · '+(r.status==='cancelled'?'取消・ポイント返還済み':'交換済み（見本）')+'</p></div>'+button('内容を見る','receipt',aid(r.id),'secondary small')+'</div>';}).join(''):'<p class="subtle" style="margin-top:12px">交換すると、ここに記録が残ります。</p>')+'</div><div class="panel"><h2>ポイントの動き</h2>'+state.transactions.filter(function(t){return t.actorId===walletActor;}).slice().reverse().map(function(t){return '<div class="ledger"><span>'+({award:'活動達成による配布',redeem:'特典利用・消却',refund:'交換取消・返還'}[t.type]||t.type)+'</span><strong>'+(t.delta>0?'+':'')+t.delta+'pt</strong></div>';}).join('')+'<details><summary>デモ全体の発行・消却を確認する</summary><dl class="details"><dt>発行上限</dt><dd>'+e.cap+'pt（実証の仮設定）</dd><dt>配布済み</dt><dd>'+e.issued+'pt</dd><dt>確保中</dt><dd>'+e.reserved+'pt</dd><dt>残りの枠</dt><dd>'+e.remaining+'pt</dd><dt>純消却</dt><dd>'+e.netBurned+'pt（取消返還を差し引いた数）</dd><dt>総残高</dt><dd>'+e.totalBalances+'pt</dd></dl><p class="subtle">発行枠と特典の供給枠は別のものです。実際の交換価値や換金を保証する仕組みではありません。</p></details></div>';
  }
  function profile() {
    var me=state.actors.me, opts=M.getOpportunities(state,'me'), summary=M.getTrustSummary(state,'me'), reviews=[];
    state.activities.filter(function(a){return a.status==='completed';}).forEach(function(a){reviews=reviews.concat(M.getReviews(state,a.id,'me').filter(function(r){return r.toActorId==='me';}));});
    var yes=reviews.filter(function(r){return r.answers.keptPromise==='yes'&&r.answers.clearRole==='yes';}).length;
    return hero('MY SPACE',name('me')+'さんの、これまで。','活動で得た経験と、確認できた関わり方。ポイントの多さとは分けて記録します。')+'<div class="stats"><div class="stat"><strong>'+me.experiences.length+'</strong><span>確認済みの活動</span></div><div class="stat"><strong>'+yes+'</strong><span>約束と役割の確認</span></div><div class="stat"><strong>'+me.balance+'</strong><span>＆ポイント</span></div></div><div class="note">この履歴はあなたの確認用です。活動回数や評価で他の人を順位付けしません。約束・役割を確認できた相手は '+summary.trustedCounterparties+'人です。</div><div class="panel"><div class="row"><div><h2>確認済みの活動プロフィール</h2><p class="subtle">何を担当したかを、次の機会に伝える。</p></div>'+button('記録を見る','certificate','','secondary small')+'</div>'+(me.experiences.length?me.experiences.slice().reverse().map(function(x){return '<div class="row"><span>'+templates[x.scenario].name+'</span><span class="tag">'+(x.role==='provider'?'支える側':'頼む側')+'として参加</span></div>';}).join(''):'<p class="subtle" style="margin-top:18px">最初の活動が終わると、ここに経験が残ります。</p>')+'</div><div class="panel"><h2>選べる役割と、次の機会</h2><p class="subtle">応募できることと、実際に役割を任されることは別です。受入側と内容を確認して決めます。</p>'+opts.map(function(o){return '<div class="opportunity"><div class="row"><h3>'+esc(o.title)+'</h3><span class="tag '+(o.available?'green':'')+'">'+(o.available?'選べます':'条件を確認')+'</span></div><p>'+esc(o.reason)+'</p>'+(o.requirements.length?'<p class="subtle">条件（仮設定）：'+o.requirements.map(esc).join('・')+'</p>':'')+(o.available?'<div class="actions">'+button(o.id==='basic-match'?'活動を探す':o.id==='propose-project'?'企画を考える':'この機会を見る',o.id==='basic-match'?'nav':o.id==='activity-profile'?'certificate':'opportunity',o.id==='basic-match'?'data-view="explore"':aid(o.id),'secondary small')+'</div>':'')+'</div>';}).join('')+'<div class="demo-controls"><p>デモ操作：運営による役割の確認を試します。実際の研修・資格認定ではありません。</p><div class="actions">'+button(me.checks.orientation?'活動説明の確認済み':'活動説明の確認を記録','role-check','data-check="orientation"','secondary small',me.checks.orientation)+button(me.checks.childSafety?'子どもとの関わり方 確認済み':'子どもとの関わり方を確認','role-check','data-check="childSafety"','secondary small',me.checks.childSafety)+'</div></div></div><div class="panel"><h2>あなたが記録した希望</h2>'+((metadata.proposals||[]).length?(metadata.proposals||[]).map(function(p){var o=opts.find(function(x){return x.id===p.opportunityId;});return '<div class="opportunity"><h3>'+esc(o?o.title:'企画の相談')+'</h3><p>'+esc(p.text)+'</p><span class="tag">デモ内に保存・未送信</span></div>';}).join(''):'<p class="subtle">機会の画面で希望を記録すると、ここで確認できます。</p>')+'</div><div class="panel soft"><h3>休んでも、記録は消えません。</h3><p class="subtle">依頼や応募は誰でも利用できます。未回答を低評価にせず、相性と信頼を分けて扱います。</p></div><div class="actions">'+button('仕組みを見る','guide','','secondary')+button('このデモを最初からやり直す','reset','','secondary')+'</div>';
  }
  function openDialog(heading, body) { var d=document.getElementById('dialog'); d.innerHTML='<button class="dialog-close" data-action="close" aria-label="閉じる">×</button><h2 id="dialog-title">'+heading+'</h2>'+body; if(!d.open)d.showModal(); }
  function closeDialog(){document.getElementById('dialog').close();}
  function createDialog(scenario,role,prior){var t=templates[scenario],m=prior||{};openDialog(t.name+'を'+(role==='receiver'?(scenario==='talk'?'頼む':'主催する'):'手伝う'),'<p>'+t.match+'</p><form data-form="activity" data-scenario="'+scenario+'" data-role="'+role+'"><label class="field"><span>活動のタイトル</span><input name="title" maxlength="60" value="'+esc(m.title||t.title)+'" required></label><div class="form-grid"><label class="field"><span>日時の例</span><input name="time" maxlength="80" value="'+esc(m.time||t.time)+'" required></label><label class="field"><span>集合場所の例</span><input name="place" maxlength="80" value="'+esc(m.place||t.place)+'" required></label></div><label class="field"><span>担当すること・終了条件</span><textarea name="details" maxlength="500" required>'+esc(m.details||t.scope)+'</textarea></label><div class="note">'+(scenario==='cleanup'?(role==='receiver'?'主催団体の立場を体験します。支援者5人に各10pt、主催団体に10ptの計60pt。担当者個人への配布はありません。':'あなたを含む支援者5人に各10pt、主催団体に10ptの計60ptを配布します。'):scenario==='club'?(role==='receiver'?'学校の担当者として依頼する場面です。支援者と学校に各10ptを配布し、担当者個人には配布しません。':'支援者と学校に、達成時それぞれ10ptを配布します。'):'支援者と受援者に、達成時それぞれ10pt。あなたの残高から支払う必要はありません。')+'</div><div class="actions"><button type="submit" class="button">この内容で進む</button></div></form>');}
  function reviewDialog(a,from,to){var provider=a.providerIds.includes(from);function options(label,key){return '<label class="field"><span>'+label+'</span><select name="'+key+'"><option value="">判断できない・今回は回答しない</option><option value="yes">確認できた</option><option value="partly">運営に確認してほしい</option></select></label>';}
    openDialog(name(from)+'からの振り返り','<p>相手：'+name(to)+'。双方提出または活動完了から7日後に反映します。配布量には影響しません。</p><form data-form="review" '+aid(a.id)+' data-from="'+from+'" data-to="'+to+'">'+options('合意した範囲で活動できたか','keptPromise')+options(provider?'事前に聞いた内容と実際の依頼が合っていたか':'希望や配慮事項を尊重してくれたか','clearRole')+'<label class="field"><span>また同じ相手と活動したいか（信頼とは別の相性）</span><select name="workAgain"><option value="">今は決めない</option><option value="yes">また活動したい</option><option value="no">今回はここまで</option></select></label><label class="field"><span>運営に確認してほしいこと（任意）</span><textarea name="report" maxlength="500" placeholder="デモ用の内容だけを入力してください"></textarea></label><div class="actions"><button class="button" type="submit">振り返りを提出する</button></div></form>');}
  function receipt(id){var r=state.redemptions.find(function(x){return x.id===id;});if(!r)return;openDialog('交換の記録','<div class="certificate"><span class="tag">デモの見本・実際には使えません</span><h3 style="margin-top:15px">'+esc(r.title)+'</h3><p>使用ポイント：'+r.points+'pt</p><p>状態：'+(r.status==='cancelled'?'取消・返還済み':'交換済み')+'</p><p>受付番号：'+esc(r.id)+'</p></div><p>このデモでは取消も試せます。取り消すとポイントと交換枠が戻ります。</p><div class="actions">'+button('交換を取り消して返還する','refund',aid(r.id),'secondary',r.status==='cancelled')+button('閉じる','close','','quiet')+'</div>');}
  document.addEventListener('click',function(event){var b=event.target.closest('[data-action]');if(!b||b.disabled)return;var d=b.dataset,a,id=d.id;switch(d.action){
    case 'nav':closeDialog();go(d.view);break;
    case 'create':createDialog(d.scenario,d.role);break;
    case 'open':selected=id;go('detail');break;
    case 'reserve':dispatch({type:'RESERVE_ACTIVITY',activityId:id},'内容が合意され、発行枠を確保しました。');break;
    case 'confirm':dispatch({type:'CONFIRM_COMPLETION',activityId:id,actorId:d.actor},'完了確認を記録しました。');break;
    case 'verify':dispatch({type:'VERIFY_ACTIVITY',activityId:id,actorId:'organization'},'実証担当者の確認を記録しました。');break;
    case 'award':dispatch({type:'AWARD_ACTIVITY',activityId:id},'活動実績を記録し、双方にポイントを配布しました。');break;
    case 'hold':openDialog('活動の状況を伝える','<p>配布は保留し、運営が実施内容を確認します。</p><div class="actions">'+button('途中で中断した','hold-confirm',aid(id)+' data-reason="partial"','secondary')+button('確認内容が食い違う','hold-confirm',aid(id)+' data-reason="disputed"','secondary')+'</div>');break;
    case 'hold-confirm':closeDialog();dispatch({type:'HOLD_ACTIVITY',activityId:id,reason:d.reason},'運営確認のため保留しました。');break;
    case 'cancel':openDialog('この活動を取り消しますか','<p>確保した発行枠を解放します。ポイントの配布はありません。</p><div class="actions">'+button('活動を取り消す','cancel-confirm',aid(id),'danger')+button('戻る','close','','secondary')+'</div>');break;
    case 'cancel-confirm':closeDialog();dispatch({type:'CANCEL_ACTIVITY',activityId:id},'取り消しました。');break;
    case 'resolve':dispatch({type:'RESOLVE_ACTIVITY',activityId:id,actorId:'organization',outcome:d.outcome},'担当者の対応を記録しました。');break;
    case 'review':a=state.activities.find(function(x){return x.id===id;});reviewDialog(a,d.from,d.to);break;
    case 'advance':dispatch({type:'ADVANCE_TIME',days:7},'デモ内の日時を7日進めました。');break;
    case 'repeat':a=state.activities.find(function(x){return x.id===id;});createDialog(a.scenario,a.meRole,metadata[a.id]);break;
    case 'role-check':dispatch({type:'SET_ROLE_CHECK',actorId:'me',check:d.check,value:true,verifiedBy:'organization'},'デモの確認事項を記録しました。');break;
    case 'wallet-actor':walletActor=d.actor;render();break;
    case 'filter':filter=d.filter;render();break;
    case 'redeem':var p=state.catalog.find(function(x){return x.id===id;});openDialog('この特典を選びますか','<p>'+esc(p.title)+'に'+p.points+'ptを使います。使った分は消却され、経験や信頼は減りません。</p><div class="note">これはデモです。実際の特典は発行されません。</div><div class="actions">'+button(p.points+'ptで交換する','redeem-confirm',aid(id))+button('戻る','close','','secondary')+'</div>');break;
    case 'redeem-confirm':closeDialog();if(dispatch({type:'REDEEM',actorId:walletActor,productId:id},'交換を記録しました。'))receipt(state.redemptions[state.redemptions.length-1].id);break;
    case 'receipt':receipt(id);break;
    case 'refund':var r=state.redemptions.find(function(x){return x.id===id;});if(dispatch({type:'CANCEL_REDEMPTION',redemptionId:id,actorId:r.actorId},'ポイントと交換枠を戻しました。'))receipt(id);break;
    case 'certificate':openDialog('あなたの活動プロフィール','<div class="certificate"><div class="eyebrow">YOU&I SPACE · 体験用の見本</div><h3>'+name('me')+'さんの活動記録</h3>'+state.actors.me.experiences.map(function(x){return '<p>'+templates[x.scenario].name+' · '+(x.role==='provider'?'支援者':'受援者')+'として参加</p>';}).join('')+'<p>確認済み '+state.actors.me.experiences.length+'活動</p><p>資格・能力の認定や、外部機関での評価を保証するものではありません。</p></div><div class="actions">'+button('閉じる','close','','secondary')+'</div>');break;
    case 'opportunity':var o=M.getOpportunities(state,'me').find(function(x){return x.id===id;});if(!o||!o.available){message('必要な条件を確認してください。');break;}openDialog(esc(o.title),'<p>条件に合う機会への応募を試せます。実際の役割は受入側との確認後に決まります。</p><label class="field"><span>やってみたいこと（デモ）</span><textarea id="proposal-text" maxlength="500" placeholder="例：園芸をテーマにした小さな会話会を開きたい"></textarea></label><div class="actions">'+button('希望を記録する','opportunity-save',aid(id))+'</div>');break;
    case 'opportunity-save':var value=document.getElementById('proposal-text').value.trim();if(!value){message('やってみたいことを入力してください。');break;}metadata.proposals=metadata.proposals||[];metadata.proposals.push({opportunityId:id,text:value});save();render();closeDialog();message('デモ内に希望を記録しました。実際の申込みは送信されません。');break;
    case 'guide':openDialog('支え合いが、次の機会につながる','<p>① 登録は0pt。残高に関係なく依頼・応募できます。</p><p>② 成立時に発行枠を確保し、活動の完了を確認した後、運営から双方へ配布します。</p><p>③ 相互評価はポイントと切り離し、約束や役割を確認します。未回答を低評価にしません。</p><p>④ 実績と信頼が、適した役割への紹介・活動プロフィール・企画の機会につながります。</p><p>⑤ ポイントは商品や体験に使い、使った分を消却します。消却だけで価値を保証することはできないため、発行枠と交換先を管理します。</p><div class="note">すべて端末内のデモです。両側10pt・発行枠300pt・評価期限7日は実証用の仮設定です。</div><div class="actions">'+button('閉じる','close','','secondary')+'</div>');break;
    case 'reset':openDialog('このデモを最初からやり直しますか','<p>この端末の新デモの活動・ポイント・振り返りを消して、0ptから始めます。従来アプリのデータには触れません。</p><div class="actions">'+button('0ptからやり直す','reset-confirm','','danger')+button('戻る','close','','secondary')+'</div>');break;
    case 'reset-confirm':try{localStorage.removeItem(KEY);}catch(_){}state=M.createState();registered=false;metadata={};selected=null;view='explore';walletActor='me';closeDialog();render();window.scrollTo(0,0);break;
    case 'close':closeDialog();break;
  }});
  document.addEventListener('submit',function(event){var form=event.target;if(!form.dataset.form)return;event.preventDefault();var f=new FormData(form),type=form.dataset.form;
    if(type==='register'){var n=String(f.get('name')||'').trim();if(!n||!f.get('understood'))return;state.actors.me.name=n.slice(0,20);registered=true;save();go('explore');}
    if(type==='activity'){var values={title:String(f.get('title')).trim(),time:String(f.get('time')).trim(),place:String(f.get('place')).trim(),details:String(f.get('details')).trim()};if(!values.title||!values.time||!values.place||!values.details)return;var action={type:'CREATE_ACTIVITY',scenario:form.dataset.scenario,meRole:form.dataset.role};if(dispatch(action)){selected=state.activeActivityId;metadata[selected]=values;save();closeDialog();go('detail');}}
    if(type==='review'){var answers={};['keptPromise','clearRole','workAgain'].forEach(function(k){answers[k]=f.get(k)||null;});if(dispatch({type:'SUBMIT_REVIEW',activityId:form.dataset.id,fromActorId:form.dataset.from,toActorId:form.dataset.to,answers:answers,report:String(f.get('report')||'')})){closeDialog();message('振り返りを提出しました。配布量には影響しません。');}}
  });
  window.addEventListener('storage',function(event){if(event.key!==KEY)return;try{var stored=JSON.parse(event.newValue);if(stored&&stored.registered){M.assertState(stored.state);state=stored.state;metadata=stored.metadata||{};registered=true;}else{state=M.createState();metadata={};registered=false;}closeDialog();render();message('別のタブでの変更を読み込みました。');}catch(_){message('保存データを確認できません。再読み込みしてください。');}});
  try{var stored=JSON.parse(localStorage.getItem(KEY)||'null');if(stored&&stored.registered&&stored.metadata&&typeof stored.metadata==='object'){M.assertState(stored.state);state=stored.state;registered=true;metadata=stored.metadata;}}catch(_){message('保存データを確認できなかったため、新しいデモを表示しています。');}
  if(!state)state=M.createState();
  render();
})();
