// 運営用スクリプトを実際に起動して、原本保持と再実行を確認する。接続先はローカル限定。
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { initializeApp, deleteApp } from 'firebase-admin/app';
import { getFirestore, Timestamp } from 'firebase-admin/firestore';
const host=process.env.FIRESTORE_EMULATOR_HOST;
if(!host||!/^127\.0\.0\.1:\d+$|^localhost:\d+$/.test(host)) throw new Error('ローカルFirestore Emulatorの指定が必要です。');
const project='demo-youi-migrate-privacy';
const app=initializeApp({projectId:project},project),db=getFirestore(app);
const script=fileURLToPath(new URL('./migrate-privacy.mjs',import.meta.url));
const run=apply=>promisify(execFile)(process.execPath,[script,'--project',project,...(apply?['--apply']:[])],{env:process.env});
const pair=(a,b)=>[a,b].sort().join('_');
const normal=(a,b)=>({participants:[a,b],names:{[a]:'名付けた人',[b]:'話し相手'},masked:[],lastMessage:'保存する本文',lastSender:a,updatedAt:Timestamp.now()});
let count=0;const pass=name=>{count++;console.log('PASS',name);};
try{
  assert.ok((await fetch(`http://${host}/emulator/v1/projects/${project}/databases/(default)/documents`,{method:'DELETE'})).ok);
  await db.doc('config/pointsLedger').set({ready:false});
  await db.doc('config/privacyMigration').set({ready:false});
  const anonymous={uid:'B',anon:true,title:'本人だけが読む本文',createdAt:Timestamp.now()};
  await db.doc('posts/anonymous').set(anonymous);
  await db.doc(`conversations/${pair('A','B')}`).set({...normal('A','B'),masked:['B']});
  await db.doc(`conversations/v2_${pair('A','B')}`).set({...normal('A','B'),privacySafe:true});
  await db.doc(`conversations/${pair('A','C')}`).set(normal('A','C'));
  await db.doc(`conversations/${pair('A','B')}/messages/keep`).set({senderId:'B',text:'過去の会話原本'});
  await db.doc(`conversations/${pair('B','C')}/messages/orphan`).set({senderId:'B',text:'親なし原本'});
  await db.doc('thanks/unsafe').set({fromUid:'B',toUid:'A',points:30,privacySafe:true});
  await db.doc('thanks/safe').set({fromUid:'C',toUid:'A',points:30});
  await db.doc('deals/unsafe').set({participants:['A','B'],byName:'名付けた人',otherName:'話し相手',privacySafe:true});
  await db.doc('deals/safe').set({participants:['A','C'],byName:'名付けた人',otherName:'話し相手'});
  const preview=await run(false);
  assert.equal((await db.doc(`conversations/${pair('A','B')}`).get()).data().privacySafe,undefined);
  assert.equal((await db.collection('privacyQuarantine').get()).size,0);
  assert.ok(!preview.stdout.includes('本人だけが読む本文')&&!preview.stdout.includes('保存する本文'));
  pass('dry-runは原本も保管先も変えず本文を出力しない');
  await run(true);
  assert.equal((await db.doc(`conversations/${pair('A','B')}`).get()).data().privacySafe,false);
  assert.equal((await db.doc(`conversations/v2_${pair('A','B')}`).get()).data().privacySafe,false);
  assert.equal((await db.doc('thanks/unsafe').get()).data().privacySafe,false);
  assert.equal((await db.doc('deals/unsafe').get()).data().privacySafe,false);
  pass('匿名の旧会話と同じ相手のv2会話と関連履歴を隔離する');
  assert.equal((await db.doc(`conversations/${pair('A','C')}`).get()).data().privacySafe,true);
  assert.equal((await db.doc('thanks/safe').get()).data().privacySafe,true);
  assert.equal((await db.doc('deals/safe').get()).data().privacySafe,true);
  pass('確認できた通常会話と関連履歴だけを再開する');
  const post=(await db.doc('posts/anonymous').get()).data();
  assert.equal(post.title,anonymous.title);assert.equal(post.uid,'B');assert.equal(post.anon,true);
  assert.ok(post.createdAt.isEqual(anonymous.createdAt));
  assert.equal((await db.doc(`conversations/${pair('A','B')}/messages/keep`).get()).data().text,'過去の会話原本');
  assert.equal((await db.doc(`conversations/${pair('B','C')}/messages/orphan`).get()).data().text,'親なし原本');
  assert.equal((await db.doc(`conversations/${pair('B','C')}`).get()).data().privacyTombstone,true);
  pass('旧投稿とmessages原本を残し親なし会話の再公開を防ぐ');
  const archives=await db.collection('privacyQuarantine').get();
  assert.ok(archives.size>=6);const originalArchive=archives.docs.find(d=>d.data().sourceCollection==='posts').data();
  assert.equal(originalArchive.data.title,anonymous.title);
  assert.equal((await db.doc('config/privacyMigration').get()).data().ready,true);
  assert.equal((await db.doc('config/pointsLedger').get()).data().ready,false);
  pass('保管を確認して通常会話だけを再開し送金は凍結を維持する');
  await run(true);
  const again=await db.collection('privacyQuarantine').get();
  assert.equal(again.size,archives.size);
  assert.ok(again.docs.find(d=>d.data().sourceCollection==='posts').data().quarantinedAt.isEqual(originalArchive.quarantinedAt));
  assert.equal((await db.doc(`conversations/v2_${pair('A','B')}`).get()).data().privacySafe,false);
  pass('再実行しても保管原本や最初の時刻を書き換えず匿名会話を再公開しない');
  await db.doc('config/pointsLedger').set({ready:true});
  await assert.rejects(run(true),/ready.*false/);
  pass('送金稼働中の本番移行を拒否する');
  console.log(`Privacy migration: ${count} checks passed.`);
}finally{await db.terminate();await deleteApp(app);}
